# Run from a fresh match directory: /path/to/rcssserver include=/path/to/configs/all_players_visible.conf
server::observation_mode = all_players_visible
server::json_log_file = match.json
server::fullstate_l = false
server::fullstate_r = false
