# Run from a fresh match directory: /path/to/rcssserver include=/path/to/configs/standard.conf
server::observation_mode = standard
server::json_log_file = match.json
server::fullstate_l = false
server::fullstate_r = false
